[package]
name = "aeropress"
version = "0.1.0"
authors = ["Rigellute <rigellute@gmail.com>"]
edition = "2018"

[dependencies]
stdweb = "0.4.15"

[dependencies.yew]
git = "https://github.com/DenisKolodin/yew"
